name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Please provide host IP'     
        required: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file BooksManagmentApi/Dockerfile --tag my-image-name:$(date +%s)

